sense:
    rs:
        -   id: 0
            width: 1280
            height: 720
    zed: ~

plan:
    work posture: [0, 0, 0, 0, 0, 0]
    workspace: {x: 0, y: 0, w: 1280, h: 720}
    threshold: 191
    sample:
        - puzzle_model/_0.bmp
        - puzzle_model/_1.bmp
        - puzzle_model/_2.bmp
        - puzzle_model/_3.bmp
        - puzzle_model/_4.bmp
        - puzzle_model/_5.bmp
        - puzzle_model/_6.bmp
        - puzzle_model/_7.bmp
        - puzzle_model/_8.bmp
        - puzzle_model/_9.bmp
        - puzzle_model/_10.bmp
        - puzzle_model/_11.bmp
        - puzzle_model/_12.bmp
        - puzzle_model/_13.bmp
        - puzzle_model/_14.bmp
        - puzzle_model/_15.bmp
        - puzzle_model/_16.bmp
    sucker_coord: 
        - [-42, 62.7, 99]
    target location:
        - [490,368,3.5]
        - [435,368,3.5]
        - [380,368,3.5]
        - [325,368,3.5]
        - [270,368,3.5]
        - [215,368,3.5]
        - [490,423,3.5]
        - [435,423,3.5]
        - [380,423,3.5]
        - [325,423,3.5]
        - [270,423,3.5]
        - [215,423,3.5]
        - [490,478,3.5]
        - [435,478,3.5]
        - [380,478,3.5]
        - [325,478,3.5]
        - [270,478,3.5]
        

act:
    arm: 
        ip: "192.168.0.1"
        port: 502
        operationMode: 1
        accel: 15
        feedRate: 10
        ptpSpeed: 10
        linSpeed: 600
        baseNum: 0
        base: [0, 0, 0, 0, 0, 0]
        toolNum: 0
        tool: [0, 0, 0, 0, 0, 0]
    serial controller: 
        port: "/dev/ttyUSB0"
        sucker: 
            - pin: 47

setting file: puzzle.yaml
