sensePara:
    rs:
        -   id: "0"
            width: 1280
            height: 720

planPara:
    work posture: [0, 0, 0, 0, 0, 0]
    work space: 
        x: 120
        y: 0
        w: 1080
        h: 720
    threshold: 50
    sample:
        - puzzle_model/0.jpeg
        - puzzle_model/1.jpeg
        - puzzle_model/2.jpeg
        - puzzle_model/3.jpeg
        - puzzle_model/4.jpeg
        - puzzle_model/5.jpeg
        - puzzle_model/6.jpeg
        - puzzle_model/7.jpeg
        - puzzle_model/8.jpeg
        - puzzle_model/9.jpeg
        - puzzle_model/10.jpeg
        - puzzle_model/11.jpeg
        - puzzle_model/12.jpeg
        - puzzle_model/13.jpeg
        - puzzle_model/14.jpeg
        - puzzle_model/15.jpeg
        - puzzle_model/16.jpeg
    sucker_coord: 
        - [-42, 62.7, 99]

actPara:
    arm: 
        ip: "192.168.0.1"
        port: 502
        operationMode: 1
        accel: 15
        feedRate: 10
        ptpSpeed: 10
        linSpeed: 600
        baseNum: 0
        base: [0, 0, 0, 0, 0, 0]
        toolNum: 0
        tool: [0, 0, 0, 0, 0, 0]
    serial controller: 
        port: "/dev/ttyUSB0"
        sucker: 
            - pin: 47

setting file: puzzle.yaml
